server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
      url: jdbc:mysql://localhost:8088/test?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
      username: root
      password: 761341
  jpa:
    database: MYSQL
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  devtools:
    restart:
      exclude: static/**,public/**

securityconfig:
  logouturl: /api/user/logout
  permitall: /swagger/**,/swagger-ui.html,/swagger-resources/**,/v2/**