server:
  port: 7900
  tomcat:
    uri-encoding: UTF-8
# datasource
spring:
  datasource:
      url: jdbc:mysql://localhost:8088/test?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
      username: root
      password: 761341
  jpa:
    database: MYSQL
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  oauth2:
      resource:
        jwt:
          keyUri: http://localhost:8081/oauth/token_key